# Generated by Django 6.0.1 on 2026-09-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer', '0004_alter_answer_question'),
        ('question', '0017_remove_question_q_difficulty_remove_question_warning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_meta_answers', to='answer.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_analyses', to='question.question')),
            ],
        ),
    ]
