# Generated by Django 6.0.1 on 2026-10-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_meta', '0001_initial'),
        ('question', '0017_remove_question_q_difficulty_remove_question_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_meta',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_meta', to='question.question'),
        ),
    ]
