# Generated by Django 6.0.1 on 2026-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('learning_objective', models.IntegerField(choices=[(0, 'Please select learning objective'), (1, 'LO1'), (2, 'LO2'), (3, 'LO3'), (4, 'LO4'), (5, 'LO5'), (6, 'LO6'), (7, 'LO7'), (8, 'LO8'), (9, 'LO9'), (10, 'LO10')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Please select question type'), (1, 'Diagram'), (2, 'Drag & drop'), (3, 'Multiple choice'), (4, 'MTC'), (5, 'MW'), (6, 'True/false')])),
                ('number', models.IntegerField()),
                ('answer_number', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('warning', models.IntegerField(choices=[(0, 'None'), (1, 'Warning'), (2, 'Flag')])),
            ],
        ),
    ]
