# Generated by Django 6.0.1 on 2026-01-16 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lo', models.IntegerField(choices=[(0, 'Please select learning objective'), (1, 'LO1'), (2, 'LO2'), (3, 'LO3'), (4, 'LO4'), (5, 'LO5'), (6, 'LO6'), (7, 'LO7'), (8, 'LO8'), (9, 'LO9'), (10, 'LO10')], default=0, verbose_name='learning objective')),
                ('type', models.IntegerField(choices=[(0, 'Please select question type'), (1, 'Diagram'), (2, 'Drag & drop'), (3, 'Multiple choice'), (4, 'MTC'), (5, 'MW'), (6, 'True/false')], default=0)),
                ('number', models.IntegerField(verbose_name='number of Qs of that LO & type')),
                ('sub_number', models.IntegerField(verbose_name='number of subquestions')),
                ('sub_answer_number_individual', models.IntegerField(verbose_name='number of answers for subquestion')),
                ('sub_correct_answer_individual', models.IntegerField(verbose_name='which answer for subquestion is correct')),
                ('warning', models.IntegerField(choices=[(0, 'None'), (1, 'Warning'), (2, 'Flag')], default=0)),
                ('author', models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001B2F8A34280>'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
