# Generated by Django 6.0.1 on 2026-01-16 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='learning_objective',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='me', on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000153A8E8FE80>'), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='lo',
            field=models.IntegerField(choices=[(0, 'Please select learning objective'), (1, 'LO1'), (2, 'LO2'), (3, 'LO3'), (4, 'LO4'), (5, 'LO5'), (6, 'LO6'), (7, 'LO7'), (8, 'LO8'), (9, 'LO9'), (10, 'LO10')], default=0, verbose_name='learning objective'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(verbose_name='number of Qs of that LO & type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Please select question type'), (1, 'Diagram'), (2, 'Drag & drop'), (3, 'Multiple choice'), (4, 'MTC'), (5, 'MW'), (6, 'True/false')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='warning',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Warning'), (2, 'Flag')], default=0),
        ),
    ]
