# Generated by Django 6.0.1 on 2026-01-16 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_learning_objective_question_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='sub_answer_number_individual',
            field=models.IntegerField(default=1, verbose_name='number of answers for subquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sub_correct_answer_individual',
            field=models.IntegerField(default=1, verbose_name='which answer for subquestion is correct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sub_number',
            field=models.IntegerField(default=1, verbose_name='number of subquestions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0000024C2DA33F20>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
