# Generated by Django 6.0.1 on 2026-01-24 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_author_alter_question_lo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000185DA234410>'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='lo',
            field=models.IntegerField(choices=[(1, 'LO1 blahblah'), (2, 'LO2 blahblah'), (3, 'LO3 blahblah'), (4, 'LO4 blahblah'), (5, 'LO5 blahblah'), (6, 'LO6 blahblah'), (7, 'LO7 blahblah'), (8, 'LO8 blahblah'), (9, 'LO9 blahblah'), (10, 'LO10 blahblah')], verbose_name='learning objective'),
        ),
    ]
