# Generated by Django 6.0.1 on 2026-01-24 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_author_alter_question_lo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0000024C7CA34410>'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='lo',
            field=models.IntegerField(choices=[(1, 'LO1'), (2, 'LO2'), (3, 'LO3'), (4, 'LO4'), (5, 'LO5'), (6, 'LO6'), (7, 'LO7'), (8, 'LO8'), (9, 'LO9'), (10, 'LO10')], verbose_name='learning objective'),
        ),
    ]
