# Generated by Django 6.0.1 on 2026-01-28 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_author_alter_question_lo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_difficulty',
            field=models.IntegerField(choices=[(0, 'Error in calculation'), (1, 'Easy'), (2, 'Optimal'), (3, 'Difficult')], default=0, verbose_name='question difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000002607E034050>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
