# Generated by Django 6.0.1 on 2026-02-12 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question_slug_alter_question_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='to edit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000229DA53BF20>'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='lo',
            field=models.IntegerField(choices=[(1, 'LO1 To understand the historical framework of ASPA and the ethics behind it.'), (2, 'LO2 To state what the ethical framework which underpins ASPA is and how programs of work are justified, by weighing likely adverse effects on the animals against the likely benefits.'), (3, 'LO3 To define the 3Rs. Indicate what they are for and how these relate to ethical principles.'), (4, 'LO4 To identify relevant sources of information relating to ethics and the 3Rs.'), (5, 'LO5 To identify ethical and animal welfare issues in their own work.'), (6, 'LO6 To explain the limits of what is considered permissible to do within a research establishment and how cultural, national, temporal, and institutional factors can differ.'), (7, 'LO7 To discuss to what extent welfare issues, pain, suffering, distress, and lasting harm should be interpreted.'), (8, 'LO8 To explain what a culture of care is, its importance, and how they may contribute.'), (9, 'LO9 To recognise the importance of ethical responsibility and identify the consequences of their actions—connected to culture of care.'), (10, 'LO10 To explain the purpose of the local AWERB.')], verbose_name='learning objective'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Diagram'), (2, 'Drag & drop'), (3, 'Multiple choice'), (4, 'Matching'), (5, 'Missing word'), (6, 'True/false')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='warning',
            field=models.IntegerField(choices=[(0, 'Error in calculation'), (1, 'None'), (2, 'Warning'), (3, 'Flag')], default=0),
        ),
    ]
