# Generated by Django 6.0.1 on 2026-02-16 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_alter_question_author_alter_question_lo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['lo', 'type', 'number']},
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001F63BD4ABC0>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
