# Generated by Django 6.0.1 on 2026-02-22 16:17

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_alter_question_answer1_alter_question_answer2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000002489CEAEC60>'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=20, populate_from='id', unique=True),
        ),
    ]
