# Generated by Django 6.0.1 on 2026-04-01 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_question_author_alter_question_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001FC1CCE8370>'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_correct_answer_individual',
            field=models.IntegerField(choices=[(1, 'Answer1'), (2, 'Answer2'), (3, 'Answer3'), (4, 'Answer4'), (5, 'Answer5')], verbose_name='which answer for subquestion is correct'),
        ),
        migrations.AlterField(
            model_name='question',
            name='warning',
            field=models.IntegerField(choices=[(0, 'Error in calculation'), (1, 'None'), (2, 'Warning'), (3, 'Flagged to revise question wording')], default=0),
        ),
    ]
