# Generated by Django 6.0.1 on 2026-09-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_alter_question_author_alter_question_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='warning',
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='lo',
            field=models.IntegerField(choices=[(1, 'LO1 To understand the historical framework of ASPA and the ethics behind it.'), (2, 'LO2 To state what the ethical framework which underpins ASPA is and how programs of work are justified, by weighing likely adverse effects on the animals against the likely benefits.'), (3, 'LO3 To define the 3Rs. Indicate what they are for and how these relate to ethical principles.'), (4, 'LO4 To identify relevant sources of information relating to ethics and the 3Rs.'), (5, 'LO5 To identify ethical and animal welfare issues in their own work.'), (6, 'LO6 To explain the limits of what is considered permissible to do within a research establishment and how cultural, national, temporal, and institutional factors can differ.'), (7, 'LO7 To discuss to what extent welfare issues, pain, suffering, distress, and lasting harm should be interpreted.'), (8, 'LO8 To explain what a culture of care is, its importance, and how they may contribute.'), (9, 'LO9 To recognise the importance of ethical responsibility and identify the consequences of their actions—connected to culture of care.'), (10, 'LO10 To explain the purpose of the local AWERB.'), (11, 'LO11 To explain the Five Freedoms and how these apply to laboratory species.'), (12, 'LO12 To describe the concept of harms to animals including avoidable and unavoidable suffering, direct, contingent, and cumulative suffering.'), (13, "LO13 To describe the importance of good animal welfare including its' effect on scientific outcomes as well as for societal and moral reasons."), (14, 'LO14 To describe the responsibility of humans when working with research animals and recognise the importance of having a respectful and humane attitude towards working with animals in research.')], verbose_name='learning objective'),
        ),
    ]
