# Generated by Django 6.0.1 on 2026-04-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0014_alter_question_author_and_more'),
        ('test', '0015_test_t_questions_alter_test_participant_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.IntegerField(default=0)),
                ('answer2', models.IntegerField(default=0)),
                ('answer3', models.IntegerField(default=0)),
                ('answer4', models.IntegerField(default=0)),
                ('answer5', models.IntegerField(default=0)),
                ('teaching_warning', models.IntegerField(choices=[(0, 'Error in calculation'), (1, 'None'), (2, 'Warning'), (3, 'Flagged to revise teaching method')], default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='question.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='test.test')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
    ]
