# Generated by Django 6.0.1 on 2026-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tester',
        ),
    ]
