# Generated by Django 6.0.1 on 2026-05-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_answer_options_remove_answer_tester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='teaching_warning',
        ),
    ]
