# Generated by Django 6.0.1 on 2026-09-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_remove_answer_teaching_warning'),
        ('question', '0017_remove_question_q_difficulty_remove_question_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_answers', to='question.question'),
        ),
    ]
