# Generated by Django 6.0.1 on 2026-01-28 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Test'), (1, 'Resit'), (2, 'AB')])),
                ('participant_number', models.IntegerField()),
                ('t_difficulty', models.IntegerField(choices=[(0, 'Error in calculation'), (1, 'Easy'), (2, 'Optimal'), (3, 'Difficult')], default=0, verbose_name='test difficulty')),
                ('tester', models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000002607E034050>'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
