# Generated by Django 6.0.1 on 2026-01-29 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default='lol', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001A50ECE44B0>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
