# Generated by Django 6.0.1 on 2026-02-16 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_alter_test_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001F63BD4ABC0>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
