# Generated by Django 6.0.1 on 2026-04-01 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_alter_question_author_and_more'),
        ('test', '0014_alter_test_date_alter_test_slug_alter_test_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='t_questions',
            field=models.ManyToManyField(to='question.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='participant_number',
            field=models.IntegerField(verbose_name='number of participants'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001FC1CCE8370>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
