# Generated by Django 6.0.1 on 2026-04-02 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0015_test_t_questions_alter_test_participant_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000200B0A2AF30>'), to=settings.AUTH_USER_MODEL),
        ),
    ]
