# Generated by Django 6.0.1 on 2026-05-01 18:09

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0016_alter_test_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=25, populate_from='id', unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
