# Generated by Django 6.0.1 on 2026-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0017_alter_test_id_alter_test_slug_alter_test_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(choices=[(0, 'E1/L PiLAB Test'), (1, 'PiLAB Test'), (2, 'Resit')]),
        ),
    ]
