# Generated by Django 6.0.1 on 2026-09-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_question_q_difficulty_remove_question_warning_and_more'),
        ('test', '0018_alter_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='t_difficulty',
        ),
        migrations.AlterField(
            model_name='test',
            name='t_questions',
            field=models.ManyToManyField(related_name='q_pool', to='question.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
