# Generated by Django 6.0.1 on 2026-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_question_q_difficulty_remove_question_warning_and_more'),
        ('test', '0019_remove_test_t_difficulty_alter_test_t_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='t_questions',
            field=models.ManyToManyField(related_name='question_pool', to='question.question'),
        ),
    ]
